[package]
name = "stream-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
axum = "0.5.7"
tokio = { version = "1.19.2", features = ["full"] }
